<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC6-DX-6C7DNK2" name="Test" tests="9" failures="2" timestamp="27 Aug 2019 05:10:59 GMT" time="0.062" errors="0">
  <testcase name="f" time="0.005" classname="Preethi_T_Day1.Annotations_All"/>
  <testcase name="display1" time="0.002" classname="Preethi_T_Day1.Annotations_All_demo"/>
  <testcase name="display2" time="0.001" classname="Preethi_T_Day1.Annotations_All_demo"/>
  <testcase name="testLogin" time="0.001" classname="Preethi_T_Day1.Credentials"/>
  <testcase name="testLogin" time="0.004" classname="Preethi_T_Day1.Credentials"/>
  <testcase name="f" time="0.002" classname="Preethi_T_Day1.HardAssertions">
    <failure type="java.lang.AssertionError" message="expected [20] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [10]
	at Preethi_T_Day1.HardAssertions.f(HardAssertions.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="testTwitter" time="0.001" classname="Preethi_T_Day1.Priority"/>
  <testcase name="testGoogle" time="0.001" classname="Preethi_T_Day1.Priority"/>
  <testcase name="f" time="0.005" classname="Preethi_T_Day1.SoftAssertions">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [20] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [20] but found [10]
	at Preethi_T_Day1.SoftAssertions.f(SoftAssertions.java:14)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
